name: say_task
description: "Voice To-Do & Smart Notes"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  hive_flutter: ^1.1.0
  speech_to_text: ^7.0.0
  flutter_local_notifications: ^18.0.1
  android_alarm_manager_plus: ^5.0.0
  timezone: ^0.10.0
  intl: ^0.19.0
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  gap: ^3.0.1
  flutter_animate: ^4.5.1
  uuid: ^4.5.1
  go_router: ^14.7.2
  path_provider: ^2.1.5
  hive: ^2.2.3
  shared_preferences: ^2.3.3
  package_info_plus: ^8.1.2
  animated_list_plus: ^0.5.2
  flutter_timezone: ^5.0.1
  home_widget: ^0.8.1
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.2.1
  path: ^1.9.1
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk must be < 21 

flutter:
  uses-material-design: true
